module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Beginner',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Training',
          items: [
            'beginner/training/module-1',
            'beginner/training/module-2',
            'beginner/training/module-3',
            'beginner/training/module-4',
            'beginner/training/module-5',
            'beginner/training/module-6',
            'beginner/training/module-7',
            'beginner/training/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Flashcards',
          items: [
            'beginner/flashcards/module-1',
            'beginner/flashcards/module-2',
            'beginner/flashcards/module-3',
            'beginner/flashcards/module-4',
            'beginner/flashcards/module-5',
            'beginner/flashcards/module-6',
            'beginner/flashcards/module-7',
            'beginner/flashcards/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Practice',
          items: [
            'beginner/practice/module-1',
            'beginner/practice/module-2',
            'beginner/practice/module-3',
            'beginner/practice/module-4',
            'beginner/practice/module-5',
            'beginner/practice/module-6',
            'beginner/practice/module-7',
            'beginner/practice/module-8',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Intermediate',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Training',
          items: [
            'intermediate/training/module-1',
            'intermediate/training/module-2',
            'intermediate/training/module-3',
            'intermediate/training/module-4',
            'intermediate/training/module-5',
            'intermediate/training/module-6',
            'intermediate/training/module-7',
            'intermediate/training/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Flashcards',
          items: [
            'intermediate/flashcards/module-1',
            'intermediate/flashcards/module-2',
            'intermediate/flashcards/module-3',
            'intermediate/flashcards/module-4',
            'intermediate/flashcards/module-5',
            'intermediate/flashcards/module-6',
            'intermediate/flashcards/module-7',
            'intermediate/flashcards/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Practice',
          items: [
            'intermediate/practice/module-1',
            'intermediate/practice/module-2',
            'intermediate/practice/module-3',
            'intermediate/practice/module-4',
            'intermediate/practice/module-5',
            'intermediate/practice/module-6',
            'intermediate/practice/module-7',
            'intermediate/practice/module-8',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Training',
          items: [
            'advanced/training/module-1',
            'advanced/training/module-2',
            'advanced/training/module-3',
            'advanced/training/module-4',
            'advanced/training/module-5',
            'advanced/training/module-6',
            'advanced/training/module-7',
            'advanced/training/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Flashcards',
          items: [
            'advanced/flashcards/module-1',
            'advanced/flashcards/module-2',
            'advanced/flashcards/module-3',
            'advanced/flashcards/module-4',
            'advanced/flashcards/module-5',
            'advanced/flashcards/module-6',
            'advanced/flashcards/module-7',
            'advanced/flashcards/module-8',
          ],
        },
        {
          type: 'category',
          label: 'Practice',
          items: [
            'advanced/practice/module-1',
            'advanced/practice/module-2',
            'advanced/practice/module-3',
            'advanced/practice/module-4',
            'advanced/practice/module-5',
            'advanced/practice/module-6',
            'advanced/practice/module-7',
            'advanced/practice/module-8',
          ],
        },
      ],
    },
  ],
};
